# Generated by Django 5.2 on 2025-06-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productapproval',
            name='sold_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
