# Generated by Django 5.2 on 2025-06-09 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_productapproval_sold_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='productapproval',
            name='average_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='productapproval',
            name='total_ratings',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
