# Generated by Django 5.2 on 2025-07-24 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_productapproval_average_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_table',
            name='new_order_alert',
            field=models.BooleanField(default=False),
        ),
    ]
