# Generated by Django 5.2 on 2025-08-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_user_table_new_order_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_table',
            name='profile_image',
            field=models.ImageField(default='profile_images/default.jpg', upload_to='profile_images/'),
        ),
    ]
