# Generated by Django 5.2 on 2025-08-25 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_user_table_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_table',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
