# Generated by Django 5.2 on 2025-08-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_alter_user_table_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_table',
            name='profile_image',
            field=models.ImageField(default='profile_images/profile_icon.jpg', upload_to='profile_images/'),
        ),
    ]
